// flow-typed signature: b22f500177baefc0230e049f8c0dae95
// flow-typed version: <<STUB>>/firebase_v4.5.2/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'firebase'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'firebase' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'firebase/app/index' {
  declare module.exports: any;
}

declare module 'firebase/auth/index' {
  declare module.exports: any;
}

declare module 'firebase/database/index' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-app-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-app-internal-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-auth-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-client-auth-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-database-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-database-internal-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-error-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-messaging-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-storage-externs' {
  declare module.exports: any;
}

declare module 'firebase/firebase-app' {
  declare module.exports: any;
}

declare module 'firebase/firebase-auth' {
  declare module.exports: any;
}

declare module 'firebase/firebase-database' {
  declare module.exports: any;
}

declare module 'firebase/firebase-firestore' {
  declare module.exports: any;
}

declare module 'firebase/firebase-messaging' {
  declare module.exports: any;
}

declare module 'firebase/firebase-storage' {
  declare module.exports: any;
}

declare module 'firebase/firebase' {
  declare module.exports: any;
}

declare module 'firebase/firestore/index' {
  declare module.exports: any;
}

declare module 'firebase/index.node' {
  declare module.exports: any;
}

declare module 'firebase/index.react-native' {
  declare module.exports: any;
}

declare module 'firebase/messaging/index' {
  declare module.exports: any;
}

declare module 'firebase/storage/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'firebase/app/index.js' {
  declare module.exports: $Exports<'firebase/app/index'>;
}
declare module 'firebase/auth/index.js' {
  declare module.exports: $Exports<'firebase/auth/index'>;
}
declare module 'firebase/database/index.js' {
  declare module.exports: $Exports<'firebase/database/index'>;
}
declare module 'firebase/externs/firebase-app-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-app-externs'>;
}
declare module 'firebase/externs/firebase-app-internal-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-app-internal-externs'>;
}
declare module 'firebase/externs/firebase-auth-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-auth-externs'>;
}
declare module 'firebase/externs/firebase-client-auth-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-client-auth-externs'>;
}
declare module 'firebase/externs/firebase-database-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-database-externs'>;
}
declare module 'firebase/externs/firebase-database-internal-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-database-internal-externs'>;
}
declare module 'firebase/externs/firebase-error-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-error-externs'>;
}
declare module 'firebase/externs/firebase-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-externs'>;
}
declare module 'firebase/externs/firebase-messaging-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-messaging-externs'>;
}
declare module 'firebase/externs/firebase-storage-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-storage-externs'>;
}
declare module 'firebase/firebase-app.js' {
  declare module.exports: $Exports<'firebase/firebase-app'>;
}
declare module 'firebase/firebase-auth.js' {
  declare module.exports: $Exports<'firebase/firebase-auth'>;
}
declare module 'firebase/firebase-database.js' {
  declare module.exports: $Exports<'firebase/firebase-database'>;
}
declare module 'firebase/firebase-firestore.js' {
  declare module.exports: $Exports<'firebase/firebase-firestore'>;
}
declare module 'firebase/firebase-messaging.js' {
  declare module.exports: $Exports<'firebase/firebase-messaging'>;
}
declare module 'firebase/firebase-storage.js' {
  declare module.exports: $Exports<'firebase/firebase-storage'>;
}
declare module 'firebase/firebase.js' {
  declare module.exports: $Exports<'firebase/firebase'>;
}
declare module 'firebase/firestore/index.js' {
  declare module.exports: $Exports<'firebase/firestore/index'>;
}
declare module 'firebase/index' {
  declare module.exports: $Exports<'firebase'>;
}
declare module 'firebase/index.js' {
  declare module.exports: $Exports<'firebase'>;
}
declare module 'firebase/index.node.js' {
  declare module.exports: $Exports<'firebase/index.node'>;
}
declare module 'firebase/index.react-native.js' {
  declare module.exports: $Exports<'firebase/index.react-native'>;
}
declare module 'firebase/messaging/index.js' {
  declare module.exports: $Exports<'firebase/messaging/index'>;
}
declare module 'firebase/storage/index.js' {
  declare module.exports: $Exports<'firebase/storage/index'>;
}
